You/todo
RedrockMobile/CyxbsMobile_Android pull request #484
Opened 2024-09-03 15:04 UTC by sanhuzhen

邮子清单迭代

2024-09-05 08:39 UTC, Gentlemuqiu approved these changes, later dismissed

2024-09-05 14:11 UTC, 985892345 commented on module_affair/src/main/java/com/mredrock/cyxbs/affair/ui/fragment/AddAffairFragment.kt
> +      }
奇怪的锁进，跟上一个}在同一级

2024-09-05 14:11 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/TodoAllAdapter.kt
> +    var isEnabled = false
会被外部调用吗，不会的话使用private修饰

2024-09-05 14:11 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/TodoAllAdapter.kt
> +        holder.listtext.viewTreeObserver.addOnGlobalLayoutListener(object :
1. 为什么要在onBind中new这种对象
2. 为什么要使用到OnGlobalLayout，我理解这个东西不是很常使用的，是否有其他替代方式？比如View#doOnNextLayout或者View#addOnLayoutChangedListener?

2024-09-05 14:11 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/TodoAllAdapter.kt
> +        @RequiresApi(Build.VERSION_CODES.O)
怎么还用到给方法限制版本了？建议使用if进行判断，而不是给方法添加

2024-09-05 14:11 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/model/database/TodoDataBase.kt
> +                            Executors.newSingleThreadExecutor().execute {
为什么要自己new一个线程池，是否可以使用Rxjava这类已有的线程池进行操作。
还有一点这里缩进太长了，建议优化代码

2024-09-05 14:28 UTC, 985892345 commented on module_todo/build.gradle.kts
> +dependAndroidView()
dependLifecycleKtx 和 dependAndroidView 我记得已经默认添加了，可以不用重复添加

2024-09-05 14:28 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/SwipeDeleteRecyclerView.kt
> +    override fun onInterceptTouchEvent(e: MotionEvent): Boolean {
重写rv的触摸事件是为了解决什么滑动冲突吗？我希望你是能理解你写的这部分代码造成的影响，而不是简单看了某篇博客就这样写了

2024-09-05 14:28 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/SwipeDeleteRecyclerView.kt
> +                parent.requestDisallowInterceptTouchEvent(false)
你这一句其实不会有任何的效果，requestDisallowInterceptTouchEvent会设置一个标记位，每次down时都会重置的

2024-09-05 14:28 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/SwipeDeleteRecyclerView.kt
> +import TodoAllAdapter
不是，哥们，你这TodoAllAdapter没有package的吗

2024-09-05 14:28 UTC, 985892345 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/DragAndDropCallback.kt
> +import androidx.core.content.ContextCompat
这个包下的类都没package

2024-09-05 14:29 UTC, 985892345 commented
所有comment都解决后再合入

2024-09-05 15:17 UTC, a1607869392 commented on module_todo/src/main/java/com/cyxbsmobile_single/module_todo/adapter/SwipeDeleteRecyclerView.kt
> +    override fun onInterceptTouchEvent(e: MotionEvent): Boolean {
解决vp2和rv侧滑的滑动冲突

2024-09-06 14:41 UTC, 985892345 approved these changes

2024-09-06 14:42 UTC, 985892345 commented
未发现啥问题，辛苦其他学长看看

2024-09-06 14:50 UTC, 985892345 requested changes

2024-09-06 14:50 UTC, 985892345 commented on build-logic/plugin/checker/src/main/kotlin/rule/ModuleNamespaceCheckRule.kt
> +//    "module_todo" to "com.cyxbsmobile_single.module_todo",
这种要删就删掉，别注释又不删

2024-09-06 15:03 UTC, 985892345 approved these changes

2024-09-07 05:12 UTC, lytMoon approved these changes

2024-09-07 05:12 UTC, lytMoon commented on module_todo/src/main/res/layout/todo_widget_todo_list_item.xml
text直接硬编码吗？也不是不可以？

2024-09-07 05:42 UTC, merged