调整搜索学生课表部分ui、开放体育打卡
RedrockMobile/CyxbsMobile_Android pull request #501
Opened 2024-11-16 14:06 UTC by lytMoon

2024-11-16 14:11 UTC, Gentlemuqiu submitted a review, later dismissed

2024-11-16 16:46 UTC, 985892345 submitted a review, later dismissed

2024-11-16 16:46 UTC, 985892345 commented on module_course/src/main/java/com/mredrock/cyxbs/course/page/find/ui/find/adapter/ShowStuResultRvAdapter.kt
> +    private fun dpToPx(dp: Int): Int {
使用已有的Int.dp2px扩展吧

2024-11-16 16:46 UTC, 985892345 commented on module_course/src/main/java/com/mredrock/cyxbs/course/page/find/ui/find/adapter/ShowStuResultRvAdapter.kt
> +          setMaxWidth(maxWidth)
不理解为什么要这里设置maxWidth，是不是可以在xml中限制宽度呢？只需要加下这个tv的右边约束即可

2024-11-16 16:53 UTC, 985892345 commented on module_course/src/main/java/com/mredrock/cyxbs/course/page/find/ui/find/adapter/ShowStuResultRvAdapter.kt
> +          setMaxWidth(maxWidth)
课表这问题我来修改吧

2024-11-17 04:53 UTC, lytMoon commented on module_course/src/main/java/com/mredrock/cyxbs/course/page/find/ui/find/adapter/ShowStuResultRvAdapter.kt
> +          setMaxWidth(maxWidth)
布局吧，我看用的约束布局，就动态适配了。ok，我这边先回退

2024-11-17 04:59 UTC, lytMoon reviewed
已drop

2024-11-17 05:04 UTC, lytMoon reviewed
drop

2024-11-17 05:05 UTC, lytMoon commented on module_course/src/main/java/com/mredrock/cyxbs/course/page/find/ui/find/adapter/ShowStuResultRvAdapter.kt
> +    private fun dpToPx(dp: Int): Int {
done

2024-11-17 05:06 UTC, 985892345 requested changes

2024-11-17 05:06 UTC, 985892345 commented on module_sport/src/main/java/com/mredrock/cyxbs/sport/ui/activity/SportDetailActivity.kt
> +//        }
注释掉的代码能删就删，而且这个sSpIdsIsBind的逻辑可以一起删掉，如果后续不再需要端上绑定jwzx后

2024-11-17 05:10 UTC, lytMoon reviewed
done

2024-11-17 05:12 UTC, 985892345 requested changes

2024-11-17 05:12 UTC, 985892345 commented on module_course/src/main/java/com/mredrock/cyxbs/course/page/find/ui/find/adapter/ShowStuResultRvAdapter.kt
> +          setMaxWidth(maxWidth)
你这里也没drop掉啊

2024-11-17 05:12 UTC, 985892345 commented on module_sport/src/main/java/com/mredrock/cyxbs/sport/ui/activity/SportDetailActivity.kt
> +//        }
这个问题你没解决吧

2024-11-17 05:12 UTC, 985892345 commented on module_sport/src/main/java/com/mredrock/cyxbs/sport/ui/activity/SportDetailActivity.kt
> -        if (!sSpIdsIsBind) {
sSpIdsIsBind的逻辑没干掉啊，辛苦删一下

2024-11-17 05:13 UTC, lytMoon commented on module_course/src/main/java/com/mredrock/cyxbs/course/page/find/ui/find/adapter/ShowStuResultRvAdapter.kt
> +          setMaxWidth(maxWidth)
刚回退，现在ok了

2024-11-17 05:17 UTC, 985892345 commented
DiscoverSportFeedViewModel#isBind还涉及了业务状态，还有一个IBindService、BindActivity，如果目前不再需要绑定统一认证码，理应一起删掉的

2024-11-17 05:18 UTC, lytMoon commented
> DiscoverSportFeedViewModel#isBind还涉及了业务状态，还有一个IBindService、BindActivity，如果目前不再需要绑定统一认证码，理应一起删掉的

后续不确定要用，我这边先把相关都下吧

2024-11-17 05:19 UTC, 985892345 commented
> DiscoverSportFeedViewModel#isBind还涉及了业务状态，还有一个IBindService、BindActivity，如果目前不再需要绑定统一认证码，理应一起删掉的

辛苦@RedSun-V 前来确认，这块之前是你在负责

2024-11-17 05:19 UTC, lytMoon commented
> DiscoverSportFeedViewModel#isBind还涉及了业务状态，还有一个IBindService、BindActivity，如果目前不再需要绑定统一认证码，理应一起删掉的

why代码，辛苦王哥review下

2024-11-17 05:24 UTC, RedSun-V commented
如果不需要 ids 认证，可以去掉，之前这里主要是爬数据要用的

2024-11-17 05:25 UTC, RedSun-V commented
找后端确认下接口是否依赖 ids 认证吧

2024-11-17 05:26 UTC, 985892345 requested changes

2024-11-17 05:26 UTC, 985892345 commented on module_sport/src/main/java/com/mredrock/cyxbs/sport/ui/activity/SportDetailActivity.kt
> -        if (!sSpIdsIsBind) {
还有设置成true的逻辑如果不用了也要一起干掉

2024-11-17 05:29 UTC, RedSun-V commented on module_sport/src/main/java/com/mredrock/cyxbs/sport/ui/activity/SportDetailActivity.kt
> -        if (!sSpIdsIsBind) {
sSpIdsIsBind 逻辑可以干掉，BindActivity 是否考虑留一下？不确定 ids 认证会不会重出江湖

2024-11-17 05:31 UTC, lytMoon commented
> 找后端确认下接口是否依赖 ids 认证吧

之前确定是不用，换新接口，我都下掉了，具体都有哪些呢？cc @985892345 @RedSun-V 
目前发现有SPTable ，相关赋值
BindActivity
/**
 * @Author: xgl
 * @ClassName: BindActivity
 * @Description:
 * @Date: 2020/9/13 19:17
 */
 
 
 IBindService 确认无误我这边都下掉了

2024-11-17 05:34 UTC, RedSun-V commented
> > 找后端确认下接口是否依赖 ids 认证吧
> 
> 之前确定是不用，换新接口，我都下掉了，具体都有哪些呢？cc @985892345 @RedSun-V 目前发现有SPTable ，相关赋值 BindActivity /**
> 
> * @author: xgl
> * @classname: BindActivity
> * @description:
> * @Date: 2020/9/13 19:17
>   */
> 
> IBindService 确认无误我这边都下掉了

不依赖 ids 认证的话，建议假刷新一起下掉，改为真刷新，之前是避免封控做的这个逻辑

2024-11-17 05:34 UTC, lytMoon commented
> > > 找后端确认下接口是否依赖 ids 认证吧
> > 
> > 
> > 之前确定是不用，换新接口，我都下掉了，具体都有哪些呢？cc @985892345 @RedSun-V 目前发现有SPTable ，相关赋值 BindActivity /**
> > 
> > * @author: xgl
> > * @classname: BindActivity
> > * @description:
> > * @Date: 2020/9/13 19:17
> >   */
> > 
> > IBindService 确认无误我这边都下掉了
> 
> 不依赖 ids 认证的话，建议假刷新一起下掉，改为真刷新，之前是避免封控做的这个逻辑

假刷新是哪里代码？

2024-11-17 05:36 UTC, 985892345 commented
> > 找后端确认下接口是否依赖 ids 认证吧
> 
> 之前确定是不用，换新接口，我都下掉了，具体都有哪些呢？cc @985892345 @RedSun-V 目前发现有SPTable ，相关赋值 BindActivity /**
> 
> * @author: xgl
> * @classname: BindActivity
> * @description:
> * @Date: 2020/9/13 19:17
>   */
> 
> IBindService 确认无误我这边都下掉了

我大致看了下，你需要改动 DiscoverSportFeedFragment、DiscoverSportFeedViewModel、IBindService、BindServiceImpl、BindActivity、BindViewModel、BindIdsApiService、IdsStatus、IdsBean
辛苦 @RedSun-V 进行确认

2024-11-17 05:39 UTC, 985892345 commented
> > > > 找后端确认下接口是否依赖 ids 认证吧
> > > 
> > > 
> > > 之前确定是不用，换新接口，我都下掉了，具体都有哪些呢？cc @985892345 @RedSun-V 目前发现有SPTable ，相关赋值 BindActivity /**
> > > 
> > > * @author: xgl
> > > * @classname: BindActivity
> > > * @description:
> > > * @Date: 2020/9/13 19:17
> > >   */
> > > 
> > > IBindService 确认无误我这边都下掉了
> > 
> > 
> > 不依赖 ids 认证的话，建议假刷新一起下掉，改为真刷新，之前是避免封控做的这个逻辑
> 
> 假刷新是哪里代码？

SportDetailActivity 63行

2024-11-17 05:44 UTC, lytMoon commented
> > > > > 找后端确认下接口是否依赖 ids 认证吧
> > > > 
> > > > 
> > > > 之前确定是不用，换新接口，我都下掉了，具体都有哪些呢？cc @985892345 @RedSun-V 目前发现有SPTable ，相关赋值 BindActivity /**
> > > > 
> > > > * @author: xgl
> > > > * @classname: BindActivity
> > > > * @description:
> > > > * @Date: 2020/9/13 19:17
> > > >   */
> > > > 
> > > > IBindService 确认无误我这边都下掉了
> > > 
> > > 
> > > 不依赖 ids 认证的话，建议假刷新一起下掉，改为真刷新，之前是避免封控做的这个逻辑
> > 
> > 
> > 假刷新是哪里代码？
> 
> SportDetailActivity 63行

已经移除相关的代码，改动较大，辛苦两位大佬重新cr下 @985892345 @RedSun-V

2024-11-17 05:47 UTC, 985892345 commented
主页有个体育打卡卡片也需要添加哈：DiscoverHomeFragment 271行

2024-11-17 05:48 UTC, RedSun-V commented
假刷新删了为什么不把真刷新加上？那刷新不是直接没了吗

2024-11-17 05:48 UTC, lytMoon commented
> DiscoverHomeFragment

真刷新是？这块我不是很熟，要不辛苦王哥新开个mr

2024-11-17 05:49 UTC, RedSun-V commented
ids 绑定界面相关代码直接删除，是确定后续不可能会再需要绑定 ids 了吗

2024-11-17 05:50 UTC, lytMoon commented
> DiscoverHomeFragment

指的是？现在体育打卡不是可以进入吗？271行代码是
    // 发现首页横排按钮点击埋点
                        functions[it].clickEvent?.let {  clickEvent ->
                            processLifecycleScope.launch {
                                TrackingUtils.trackClickEvent(clickEvent)
                            }
                        }

2024-11-17 05:50 UTC, lytMoon commented
> ids 绑定界面相关代码直接删除，是确定后续不可能会再需要绑定 ids 了吗

之前确定是换新接口

2024-11-17 05:51 UTC, lytMoon commented
> 主页有个体育打卡卡片也需要添加哈：DiscoverHomeFragment 271行

指的是？现在体育打卡不是可以进入吗？271行代码是
// 发现首页横排按钮点击埋点
functions[it].clickEvent?.let { clickEvent ->
processLifecycleScope.launch {
TrackingUtils.trackClickEvent(clickEvent)
}
}

2024-11-17 05:51 UTC, 985892345 commented
> > ids 绑定界面相关代码直接删除，是确定后续不可能会再需要绑定 ids 了吗
> 
> 之前确定是换新接口

那用户怎么登陆ids呢？还是说server那边根据我们的学号去拿的数据？

2024-11-17 05:52 UTC, lytMoon commented
> > > ids 绑定界面相关代码直接删除，是确定后续不可能会再需要绑定 ids 了吗
> > 
> > 
> > 之前确定是换新接口
> 
> 那用户怎么登陆ids呢？还是说server那边根据我们的学号去拿的数据？

现在后端改成了只需要get调用接口，带token访问

2024-11-17 05:52 UTC, 985892345 commented
> > 主页有个体育打卡卡片也需要添加哈：DiscoverHomeFragment 271行
> 
> 指的是？现在体育打卡不是可以进入吗？271行代码是 // 发现首页横排按钮点击埋点 functions[it].clickEvent?.let { clickEvent -> processLifecycleScope.launch { TrackingUtils.trackClickEvent(clickEvent) } }

就主页有todo和电费的卡片，体育打卡也是有的，在 DiscoverHomeFragment#initFeeds 里面添加，目前是注释了的

2024-11-17 05:53 UTC, RedSun-V commented
后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么

2024-11-17 05:54 UTC, lytMoon commented
> DiscoverHomeFragment



> > > 主页有个体育打卡卡片也需要添加哈：DiscoverHomeFragment 271行
> > 
> > 
> > 指的是？现在体育打卡不是可以进入吗？271行代码是 // 发现首页横排按钮点击埋点 functions[it].clickEvent?.let { clickEvent -> processLifecycleScope.launch { TrackingUtils.trackClickEvent(clickEvent) } }
> 
> 就主页有todo和电费的卡片，体育打卡也是有的，在 DiscoverHomeFragment#initFeeds 里面添加，目前是注释了的

已经恢复

2024-11-17 05:55 UTC, lytMoon commented
> 后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么

不知道呀，目前需求是只恢复体育打卡，ids后续其他模块也说不准，得问server，所以是下掉还是暂存 cc @985892345 @RedSun-V

2024-11-17 05:56 UTC, 985892345 commented
> > 后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么
> 
> 不知道呀，目前需求是只恢复体育打卡，ids后续其他模块也说不准，得问server，所以是下掉还是暂存 cc @985892345 @RedSun-V

建议下掉吧，后续也不可能上单独的ids登录了，ids登录应该会集成到掌邮登陆里面

2024-11-17 05:58 UTC, lytMoon commented
> > > 后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么
> > 
> > 
> > 不知道呀，目前需求是只恢复体育打卡，ids后续其他模块也说不准，得问server，所以是下掉还是暂存 cc @985892345 @RedSun-V
> 
> 建议下掉吧，后续也不可能上单独的ids登录了，ids登录应该会集成到掌邮登陆里面

辛苦王哥cr下，我看是王哥代码，没啥问题这边就合了，后端那边催包测试，昨天发了个测试包，搜索课表的学生界面适配问题也辛苦郭神尽快合入线上 cc @985892345 @RedSun-V

2024-11-17 05:59 UTC, 985892345 commented
> > > > 后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么
> > > 
> > > 
> > > 不知道呀，目前需求是只恢复体育打卡，ids后续其他模块也说不准，得问server，所以是下掉还是暂存 cc @985892345 @RedSun-V
> > 
> > 
> > 建议下掉吧，后续也不可能上单独的ids登录了，ids登录应该会集成到掌邮登陆里面
> 
> 辛苦王哥cr下，我看是王哥代码，没啥问题这边就合了，后端那边催包测试，昨天发了个测试包，搜索课表的学生界面适配问题也辛苦郭神尽快合入线上 cc @985892345 @RedSun-V

我觉得问题还很多呢，很多东西你都没删完的

2024-11-17 06:01 UTC, 985892345 commented
你先push上去，我来改点代码

2024-11-17 06:01 UTC, lytMoon commented
> > > > > 后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么
> > > > 
> > > > 
> > > > 不知道呀，目前需求是只恢复体育打卡，ids后续其他模块也说不准，得问server，所以是下掉还是暂存 cc @985892345 @RedSun-V
> > > 
> > > 
> > > 建议下掉吧，后续也不可能上单独的ids登录了，ids登录应该会集成到掌邮登陆里面
> > 
> > 
> > 辛苦王哥cr下，我看是王哥代码，没啥问题这边就合了，后端那边催包测试，昨天发了个测试包，搜索课表的学生界面适配问题也辛苦郭神尽快合入线上 cc @985892345 @RedSun-V
> 
> 我觉得问题还很多呢，很多东西你都没删完的

辛苦郭神再看看 这个分支是lyt/improve/new 🫡  还是可以考虑单独开个分支来下掉ids

2024-11-17 06:02 UTC, 985892345 commented
> > > > > > 后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么
> > > > > 
> > > > > 
> > > > > 不知道呀，目前需求是只恢复体育打卡，ids后续其他模块也说不准，得问server，所以是下掉还是暂存 cc @985892345 @RedSun-V
> > > > 
> > > > 
> > > > 建议下掉吧，后续也不可能上单独的ids登录了，ids登录应该会集成到掌邮登陆里面
> > > 
> > > 
> > > 辛苦王哥cr下，我看是王哥代码，没啥问题这边就合了，后端那边催包测试，昨天发了个测试包，搜索课表的学生界面适配问题也辛苦郭神尽快合入线上 cc @985892345 @RedSun-V
> > 
> > 
> > 我觉得问题还很多呢，很多东西你都没删完的
> 
> 辛苦郭神再看看 这个分支是lyt/improve/new 🫡 还是可以考虑单独开个分支来下掉ids

就一个分支操作就行了，我提新的commit

2024-11-17 06:02 UTC, lytMoon commented
> > > > > > > 后续其他模块不会再有绑定 ids 的需求了吗，都能闭环在我们 server 的服务内？客户端无感知么
> > > > > > 
> > > > > > 
> > > > > > 不知道呀，目前需求是只恢复体育打卡，ids后续其他模块也说不准，得问server，所以是下掉还是暂存 cc @985892345 @RedSun-V
> > > > > 
> > > > > 
> > > > > 建议下掉吧，后续也不可能上单独的ids登录了，ids登录应该会集成到掌邮登陆里面
> > > > 
> > > > 
> > > > 辛苦王哥cr下，我看是王哥代码，没啥问题这边就合了，后端那边催包测试，昨天发了个测试包，搜索课表的学生界面适配问题也辛苦郭神尽快合入线上 cc @985892345 @RedSun-V
> > > 
> > > 
> > > 我觉得问题还很多呢，很多东西你都没删完的
> > 
> > 
> > 辛苦郭神再看看 这个分支是lyt/improve/new 🫡 还是可以考虑单独开个分支来下掉ids
> 
> 就一个分支操作就行了，我提新的commit

收到🫡

2024-11-17 07:05 UTC, 985892345 commented
@lytMoon @RedSun-V 辛苦各位大佬再cr一下哈

2024-11-17 07:13 UTC, RedSun-V commented
考试也一起改了吗？

2024-11-17 07:14 UTC, RedSun-V approved these changes, later dismissed

2024-11-17 07:14 UTC, 985892345 commented
> 考试也一起改了吗？

一起杨了ids相关的代码，但server那边应该是没数据的

2024-11-17 07:21 UTC, 985892345 approved these changes, later dismissed

2024-11-17 09:24 UTC, merged