修改同步远端和本地的网络请求
RedrockMobile/CyxbsMobile_Android pull request #503
Opened 2024-11-17 14:24 UTC by sanhuzhen

2024-11-17 14:33 UTC, 985892345 requested changes

2024-11-17 14:33 UTC, 985892345 commented on module_todo/src/main/java/com/mredrock/cyxbs/todo/viewmodel/TodoViewModel.kt
> +                if ((it.todoArray.isNullOrEmpty() && it.syncTime == 0L) || it.syncTime < 1731836400) {
为什么会有一个1731836400的硬编码？

2024-11-17 14:33 UTC, 985892345 commented on module_todo/src/main/java/com/mredrock/cyxbs/todo/viewmodel/TodoViewModel.kt
> +        if (getLastModifyTime() > getLastSyncTime()){
过期的判断建议写成一个1秒内浮动的判断，避免因为代码执行顺序而少了几毫秒就出问题

2024-11-17 14:36 UTC, sanhuzhen commented on module_todo/src/main/java/com/mredrock/cyxbs/todo/viewmodel/TodoViewModel.kt
> +                if ((it.todoArray.isNullOrEmpty() && it.syncTime == 0L) || it.syncTime < 1731836400) {
后端那边用的是老接口，然后这个要一个新手教程，老用户时间戳肯定不是为零，所以这里要加一个条件，让老用户也要有新手教程

2024-11-17 14:38 UTC, 985892345 commented on module_todo/src/main/java/com/mredrock/cyxbs/todo/viewmodel/TodoViewModel.kt
> +                if ((it.todoArray.isNullOrEmpty() && it.syncTime == 0L) || it.syncTime < 1731836400) {
既然新老用户都要现实教程那为什么不是新写一个sp，而是用硬编码。如果一个新用户超过这个时间错会发生什么呢？

2024-11-20 05:43 UTC, 985892345 requested changes

2024-11-20 05:43 UTC, 985892345 commented on module_todo/src/main/java/com/mredrock/cyxbs/todo/viewmodel/TodoViewModel.kt
> +                    if (getLastSyncTime() > getLastModifyTime()){
这里一起修改下吧，最好直接封装成一个函数

2024-11-21 12:47 UTC, 985892345 requested changes

2024-11-21 12:47 UTC, 985892345 commented on module_todo/src/main/java/com/mredrock/cyxbs/todo/viewmodel/TodoViewModel.kt
> +        if (isTimeCompare(getLastModifyTime(), getLastSyncTime())){
不应该把过期时间的比对抽成一个函数，而应该把过期这个行为抽成一个函数

2024-11-21 14:38 UTC, merged